### ISSUE TITLE
problems with non ascii letters

### ISSUE THREAD

**Issue by Tobias-Horstmann** [OasisLMF/ITWG---AIR-CEDE-to-OED-file#12]
None ascii letters, in this case "ó" throws an error when writing the location file. Inserting "encoding='utf-8'" in the file_helper.py resolved the issue for me.

Changed code bit:
original:  OED_location_file_final.to_csv(filename, index=False)
new:        OED_location_file_final.to_csv(filename, index=False, encoding='utf-8')

Error from log file:

2019-11-14 10:42:41,826 ERROR 'ascii' codec can't encode character u'\xf3' in position 10: ordinal not in range(128)
Traceback (most recent call last):
  File "[]\AIR-CEDE-to-OED-file-master\src\file_helper.py", line 75, in output_write
    OED_location_file_final.to_csv(filename, index=False)
  File "C:\Python27\ArcGISx6410.6\lib\site-packages\pandas\core\frame.py", line 1344, in to_csv
    formatter.save()
  File "C:\Python27\ArcGISx6410.6\lib\site-packages\pandas\formats\format.py", line 1551, in save
    self._save()
  File "C:\Python27\ArcGISx6410.6\lib\site-packages\pandas\formats\format.py", line 1652, in _save
    self._save_chunk(start_i, end_i)
  File "C:\Python27\ArcGISx6410.6\lib\site-packages\pandas\formats\format.py", line 1678, in _save_chunk
    lib.write_csv_rows(self.data, ix, self.nlevels, self.cols, self.writer)
  File "pandas/lib.pyx", line 1078, in pandas.lib.write_csv_rows (pandas\lib.c:19850)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 10: ordinal not in range(128)

**Comment by sbarik5** [comment]
@Tobias-Horstmann , Thank you for looking into the issue and resolving.
